### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by asuraiv** [cossme/grinder#31]
Dear contributors.

I have a simple question. When doing performance test, I prefer to using nGrinder based on grinder. So i am researching grinder source, And then i found two repository for grinder github and sourceforge. This is my question. What different between two repository?

**Comment by solcyr** [comment]
Hello,

Last year we have create this cossme/grinder github repository, based on the latest sourceforge Grinder 3.11 label.

Sourceforge Grinder is not maintained anymore and we had the need of upgrading Grinder and adding some features (most important one is the WebUI)

Since version 4.0 Cossme Grinder is a clear fork of the Historical Grinder 3. I don't know if Grinder 4.X will works with nGrinder. 
You can either try and let us know or use the 3.11 source bundle that you can found in the release section.

Best Regards
